pub mod package_manager;
pub mod display;
pub mod init;
pub mod services;
pub mod login;
pub mod theming;
pub mod audio;
pub mod power;
pub mod network;
pub mod kernel;
pub mod bootloader;
pub mod storage;
pub mod updates;
pub mod builder;
pub mod distro;
pub mod installer;
pub mod software;
pub mod iso_builder;

use anyhow::Result;
use log::info; 